theme: jekyll-theme-cayman
avatar: pic.jpg
title: Thangjam Aditya
description: Welcome to my Website!
image:
  background: https://github.com/Simply-Adi/Simply-Adi.github.io/blob/9ce0f2d44f97c5d15ee782ee3ac685e410527954/DALL%C2%B7E%202023-06-07%2000.39.34.png
